openapi: 3.0.3
info:
  title: quizDev
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://quizdev.test'
paths:
  /api/v1/test:
    get:
      summary: ''
      operationId: getApiV1Test
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "tu es connecté à l'api quiz dev"
      tags:
        - Endpoints
      security: []
  /api/v1/auth/register:
    post:
      summary: 'POST api/v1/auth/register'
      operationId: pOSTApiv1authregister
      description: "permet de s'enregistrer"
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                lastname:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: ywgmeatjdaaaepbr
                name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: exeuamforrpmrzxwwuzeddfcs
                password:
                  type: string
                  description: ''
                  example: libero
                role_id:
                  type: string
                  description: ''
                  example: '2'
                  enum:
                    - '2'
                    - '3'
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: pearline.krajcik@example.org
              required:
                - lastname
                - name
                - password
                - role_id
                - email
      security: []
  /api/v1/auth/login:
    post:
      summary: ''
      operationId: postApiV1AuthLogin
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: ona75@example.com
                password:
                  type: string
                  description: ''
                  example: sit
              required:
                - email
                - password
      security: []
  /api/v1/profil:
    get:
      summary: ''
      operationId: getApiV1Profil
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/v1/update/profil:
    put:
      summary: ''
      operationId: putApiV1UpdateProfil
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: eldred.schneider@example.org
                name:
                  type: string
                  description: ''
                  example: dolore
                lastname:
                  type: string
                  description: ''
                  example: non
              required:
                - email
                - name
                - lastname
      security: []
  /api/v1/update/password:
    put:
      summary: ''
      operationId: putApiV1UpdatePassword
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                current_password:
                  type: string
                  description: ''
                  example: necessitatibus
                password:
                  type: string
                  description: ''
                  example: perferendis
              required:
                - current_password
                - password
      security: []
  /api/v1/logout:
    post:
      summary: ''
      operationId: postApiV1Logout
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/v1/delete/profil:
    delete:
      summary: ''
      operationId: deleteApiV1DeleteProfil
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/v1/user/quiz:
    get:
      summary: ''
      operationId: getApiV1UserQuiz
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/v1/entreprise/quiz:
    get:
      summary: ''
      operationId: getApiV1EntrepriseQuiz
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/v1/level/store:
    post:
      summary: ''
      operationId: postApiV1LevelStore
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: laudantium
                points:
                  type: integer
                  description: ''
                  example: 16
                slug:
                  type: string
                  description: ''
                  example: alias
              required:
                - name
      security: []
  /api/v1/levels:
    get:
      summary: ''
      operationId: getApiV1Levels
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/v1/level/destroy:
    delete:
      summary: ''
      operationId: deleteApiV1LevelDestroy
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                slug:
                  type: string
                  description: ''
                  example: sunt
              required:
                - slug
      security: []
  /api/v1/domains:
    get:
      summary: ''
      operationId: getApiV1Domains
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/v1/domain/store:
    post:
      summary: ''
      operationId: postApiV1DomainStore
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: aut
              required:
                - name
      security: []
  '/api/v1/domain/delete/{id}':
    delete:
      summary: ''
      operationId: deleteApiV1DomainDeleteId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the delete.'
        example: ipsa
        required: true
        schema:
          type: string
  /api/v1/questions:
    get:
      summary: ''
      operationId: getApiV1Questions
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/v1/question/store:
    post:
      summary: ''
      operationId: postApiV1QuestionStore
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 'Must not be greater than 150 characters.'
                  example: eneoxrcjw
                domain_id:
                  type: integer
                  description: ''
                  example: 14
                level_id:
                  type: integer
                  description: ''
                  example: 2
                points:
                  type: integer
                  description: ''
                  example: 4
                answers:
                  type: object
                  description: 'Must have at least 2 items.'
                  example: []
                  properties: {  }
              required:
                - title
                - domain_id
                - level_id
                - answers
      security: []
  '/api/v1/question/show/{id}':
    get:
      summary: ''
      operationId: getApiV1QuestionShowId
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the show.'
        example: dolores
        required: true
        schema:
          type: string
  '/api/v1/question/update/{id}':
    put:
      summary: ''
      operationId: putApiV1QuestionUpdateId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: 'Must not be greater than 150 characters.'
                  example: cnavojwxwa
                domain_id:
                  type: integer
                  description: ''
                  example: 17
                level_id:
                  type: integer
                  description: ''
                  example: 3
                points:
                  type: integer
                  description: ''
                  example: 19
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the update.'
        example: laborum
        required: true
        schema:
          type: string
  '/api/v1/question/delete/{id}':
    put:
      summary: ''
      operationId: putApiV1QuestionDeleteId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the delete.'
        example: qui
        required: true
        schema:
          type: string
  /api/v1/quizzes:
    get:
      summary: "GET QUIZ\nrécupérations de tous les quiz"
      operationId: gETQUIZrcuprationsDeTousLesQuiz
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/v1/quiz/store:
    post:
      summary: ''
      operationId: postApiV1QuizStore
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: ''
                  example: beatae
                level_id:
                  type: integer
                  description: ''
                  example: 7
                questions:
                  type: object
                  description: 'Must have at least 1 items.'
                  example: null
                  properties: {  }
                questions_ids:
                  type: object
                  description: 'Must have at least 1 items.'
                  example: null
                  properties: {  }
              required:
                - title
                - level_id
      security: []
tags:
  -
    name: Endpoints
    description: ''
