openapi: 3.0.3
info:
  title: quizDev
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://quizdev.test'
paths:
  /api/v1/test:
    get:
      summary: ''
      operationId: getApiV1Test
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "tu es connecté à l'api quiz dev"
      tags:
        - Endpoints
      security: []
  /api/v1/auth/register:
    post:
      summary: ''
      operationId: postApiV1AuthRegister
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                lastname:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: zimc
                name:
                  type: string
                  description: 'Must not be greater than 255 characters.'
                  example: nqoiegzfbcdfymjxlbgvzgdhj
                password:
                  type: string
                  description: ''
                  example: voluptatum
                role_id:
                  type: string
                  description: ''
                  example: '3'
                  enum:
                    - '2'
                    - '3'
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: melyssa.veum@example.org
              required:
                - lastname
                - name
                - password
                - role_id
                - email
      security: []
  /api/v1/auth/login:
    post:
      summary: ''
      operationId: postApiV1AuthLogin
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: shaylee62@example.org
                password:
                  type: string
                  description: ''
                  example: est
              required:
                - email
                - password
      security: []
  /api/v1/profil:
    get:
      summary: ''
      operationId: getApiV1Profil
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/v1/update/profil:
    put:
      summary: ''
      operationId: putApiV1UpdateProfil
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: sanford.raymond@example.com
                name:
                  type: string
                  description: ''
                  example: voluptatem
                lastname:
                  type: string
                  description: ''
                  example: dolores
              required:
                - email
                - name
                - lastname
      security: []
  /api/v1/update/password:
    put:
      summary: ''
      operationId: putApiV1UpdatePassword
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                current_password:
                  type: string
                  description: ''
                  example: similique
                password:
                  type: string
                  description: ''
                  example: nihil
              required:
                - current_password
                - password
      security: []
  /api/v1/logout:
    post:
      summary: ''
      operationId: postApiV1Logout
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/v1/user/quiz:
    get:
      summary: ''
      operationId: getApiV1UserQuiz
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/v1/entreprise/quiz:
    get:
      summary: ''
      operationId: getApiV1EntrepriseQuiz
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/v1/level/store:
    post:
      summary: 'Store the newly created resource in storage.'
      operationId: storeTheNewlyCreatedResourceInStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: alias
                points:
                  type: integer
                  description: ''
                  example: 1
                slug:
                  type: string
                  description: ''
                  example: non
              required:
                - name
      security: []
  /api/v1/levels:
    get:
      summary: ''
      operationId: getApiV1Levels
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/v1/level/destroy:
    delete:
      summary: 'Remove the resource from storage.'
      operationId: removeTheResourceFromStorage
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                slug:
                  type: string
                  description: ''
                  example: soluta
              required:
                - slug
      security: []
tags:
  -
    name: Endpoints
    description: ''
