name: CI/CD Workflow

on:
  push:
    branches:
      - Quentin

jobs:
  php_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, pdo_sqlite

    - name: Copy .env
      run: php -r "file_exists('src/.env') || copy('src/.env.example', 'src/.env');"

    - name: Update Dependencies
      run: composer update --working-dir=src

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --working-dir=src

    - name: Directory Permissions
      run: chmod -R 777 src/storage src/bootstrap/cache

    - name: Create Database
      run: |
        mkdir -p src/database
        touch src/database/database.sqlite

    - name: Execute PHPUnit Tests
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: src/database/database.sqlite
      run: src/vendor/bin/phpunit

  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  snyk_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Scan with Snyk
      run: npx snyk test --all-projects
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
